name: workflow

on:
  pull_request:
    branches: 
      - main


jobs:
  docs:
    uses: ./.github/workflows/docs.yml
  terraform:
    uses: ./.github/workflows/terraform.yml
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4